const fs = require('fs');
const RSSParser = require('rss-parser');
const parser = new RSSParser({ timeout: 5000 });

const sourcesJsPath = './services/sources.js';
let sourcesText = fs.readFileSync(sourcesJsPath, 'utf8');

// Known fixes from manual web searches
const manualFixes = {
  'scmp.com': 'https://www.scmp.com/rss',
  'cnbc.com': 'https://www.cnbc.com/id/10001147/device/rss/rss.html', // Business
  'bloomberg.com': 'https://feeds.bloomberg.com/markets/news.rss',
  'straitstimes.com': 'https://www.straitstimes.com/news/business/rss.xml',
  'bangkokpost.com': 'https://www.bangkokpost.com/rss',
  'arabnews.com': 'https://www.arabnews.com/rss',
  'thenationalnews.com': 'https://www.thenationalnews.com/business/rss',
  'economynext.com': 'https://economynext.com/feed/',
  'bdnews24.com': 'https://bdnews24.com/?widgetName=rssfeed&widgetId=1150&getXmlFeed=true',
  'bbc.com': 'https://feeds.bbci.co.uk/news/business/rss.xml'
};

const failedSources = JSON.parse(fs.readFileSync('./failed_sources.json', 'utf8'));

// Apply manual fixes first
let manualFixedCount = 0;
failedSources.forEach(f => {
  if (manualFixes[f.name]) {
    // We update the original sources code text
    // Because sources.js is a generated JS file, we'll parse it, update the JS object, and re-write
    manualFixedCount++;
  }
});
console.log(`Ready to apply ${manualFixedCount} manual fixes.`);

// Let's do it cleanly by parsing the module, modifying the exported array, and dumping it back
const sources = require('./services/sources');
let updatedSources = [...sources];

failedSources.forEach(f => {
  // If we have a manual fix, apply it and remove from failures
  if (manualFixes[f.name]) {
    const idx = updatedSources.findIndex(s => s.name === f.name);
    if (idx !== -1) {
      updatedSources[idx].url = manualFixes[f.name];
    }
  }
});

// We will also brute-force search the remaining failed ones by testing standard suffixes
const suffixes = ['/rss', '/feed', '/rss.xml', '/feed.xml'];

async function bruteForceFindRss() {
  const toTest = failedSources.filter(f => !manualFixes[f.name]);
  console.log(`Starting brute-force RSS discovery on ${toTest.length} remaining failed domains...`);

  const results = [];
  const BATCH = 30;

  for (let i = 0; i < toTest.length; i += BATCH) {
    const batch = toTest.slice(i, i + BATCH);
    
    const promises = batch.map(async (domainData) => {
      let baseUrl = domainData.url;
      // Strip off paths to get to domain root
      try {
        const u = new URL(baseUrl);
        baseUrl = u.origin;
      } catch(e) {}
      
      for (const suffix of suffixes) {
        const testUrl = baseUrl + suffix;
        try {
          const feed = await parser.parseURL(testUrl);
          if (feed && feed.items && feed.items.length > 0) {
            return { domain: domainData.name, newUrl: testUrl };
          }
        } catch (e) {
             // Fall silently
        }
      }
      return null;
    });

    const batchResults = await Promise.all(promises);
    batchResults.forEach(res => {
      if (res) results.push(res);
    });
    
    process.stdout.write(`\rBrute-force progress: ${Math.min(i + BATCH, toTest.length)}/${toTest.length}...`);
  }

  console.log(`\nFound ${results.length} valid RSS endpoints via brute-force suffix checking!`);
  
  // Apply brute-force results
  results.forEach(res => {
    const idx = updatedSources.findIndex(s => s.name === res.domain);
    if (idx !== -1) {
      updatedSources[idx].url = res.newUrl;
    }
  });

  // Write the updated sources back
  const fileContent = `// Auto-generated by Auto-Discovery Engine (Repaired)\nconst sources = ${JSON.stringify(updatedSources, null, 2)};\nmodule.exports = sources;\n`;
  fs.writeFileSync(sourcesJsPath, fileContent);
  console.log('✅ Sources array completely updated and repaired!');
}

bruteForceFindRss();
